# clingo-lpx  --------------------------------------------------------------------------------------------------------------------------------------------------
log-lpx:
	@mkdir -p ./logs 2>&1 ; rm -f ./logs/lpx-*.log 2>&1 ; exit 0

	python ../hec-incr.py ./BusRide2-ea.lp > logs/lpx-BusRide2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./BusRide40-ea.lp > logs/lpx-BusRide40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./ChessBoard2-ea.lp > logs/lpx-ChessBoard2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./ChessBoard40-ea.lp > logs/lpx-ChessBoard40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./CoinToss4-ea.lp > logs/lpx-CoinToss4-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./CoinToss40-ea.lp > logs/lpx-CoinToss40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --no_axioms ../axioms/hec_dur.lp ../axioms/hec_dur-show.lp ./Commuter15-ea.lp > logs/lpx-Commuter15-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./DeadOrAlive3-ea.lp > logs/lpx-DeadOrAlive3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./DeadOrAlive40-ea.lp > logs/lpx-DeadOrAlive40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./Happy2-ea.lp > logs/lpx-Happy2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./Happy40-ea.lp > logs/lpx-Happy40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./KitchenSink_M5-ea.lp > logs/lpx-KitchenSink_M5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./KitchenSink_M25-ea.lp > logs/lpx-KitchenSink_M25-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./KitchenSink_M40-ea.lp > logs/lpx-KitchenSink_M40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./RussianTurkey4-ea.lp > logs/lpx-RussianTurkey4-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./RussianTurkey40-ea.lp > logs/lpx-RussianTurkey40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./StolenCar2-ea.lp > logs/lpx-StolenCar2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./StolenCar40-ea.lp > logs/lpx-StolenCar40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./StuffyRoom2-ea.lp > logs/lpx-StuffyRoom2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./StuffyRoom40-ea.lp > logs/lpx-StuffyRoom40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./Supermarket12-ea.lp > logs/lpx-Supermarket12-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./Supermarket40-ea.lp > logs/lpx-Supermarket40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ../axioms/causal.lp ./ThielscherCircuit1-ea.lp > logs/lpx-ThielscherCircuit1-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ../axioms/causal.lp ./ThielscherCircuit20-ea.lp > logs/lpx-ThielscherCircuit20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ../axioms/causal.lp ./ThielscherCircuit40-ea.lp > logs/lpx-ThielscherCircuit40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./WalkingTurkey3-ea.lp > logs/lpx-WalkingTurkey3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./WalkingTurkey40-ea.lp > logs/lpx-WalkingTurkey40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./Yale3-ea.lp > logs/lpx-Yale3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./Yale40-ea.lp > logs/lpx-Yale40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./FallingObjectWithAntiTrajectory5-ea.lp > logs/lpx-FallingObjectWithAntiTrajectory5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./FallingObjectWithAntiTrajectory15-ea.lp > logs/lpx-FallingObjectWithAntiTrajectory15-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./FallingObjectWithAntiTrajectory25-ea.lp > logs/lpx-FallingObjectWithAntiTrajectory25-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./FallingObjectWithEvents5-ea.lp > logs/lpx-FallingObjectWithEvents5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./FallingObjectWithEvents20-ea.lp > logs/lpx-FallingObjectWithEvents20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./FallingObjectWithEvents25-ea.lp > logs/lpx-FallingObjectWithEvents25-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./FallingObjectWithEvents40-ea.lp > logs/lpx-FallingObjectWithEvents40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./HotAirBalloon3-ea.lp > logs/lpx-HotAirBalloon3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./HotAirBalloon15-ea.lp > logs/lpx-HotAirBalloon15-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./HotAirBalloon20-ea.lp > logs/lpx-HotAirBalloon20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./HotAirBalloon40-ea.lp > logs/lpx-HotAirBalloon40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py ./Telephone3-ea.lp > logs/lpx-Telephone3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py ./Telephone40-ea.lp > logs/lpx-Telephone40-ea.log 2>&1 ; exit 0

# clingcon  --------------------------------------------------------------------------------------------------------------------------------------------------
log-con:
	@mkdir -p ./logs 2>&1 ; rm -f ./logs/con-*.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./BusRide2-ea.lp > logs/con-BusRide2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./BusRide40-ea.lp > logs/con-BusRide40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./ChessBoard2-ea.lp > logs/con-ChessBoard2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./ChessBoard40-ea.lp > logs/con-ChessBoard40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./CoinToss4-ea.lp > logs/con-CoinToss4-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./CoinToss40-ea.lp > logs/con-CoinToss40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con --no_axioms ../axioms/hec_dur.lp ../axioms/hec_dur-show.lp ./Commuter15-ea.lp > logs/con-Commuter15-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./DeadOrAlive3-ea.lp > logs/con-DeadOrAlive3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./DeadOrAlive40-ea.lp > logs/con-DeadOrAlive40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./Happy2-ea.lp > logs/con-Happy2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./Happy40-ea.lp > logs/con-Happy40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./KitchenSink_M5-ea.lp > logs/con-KitchenSink_M5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./KitchenSink_M25-ea.lp > logs/con-KitchenSink_M25-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./KitchenSink_M40-ea.lp > logs/con-KitchenSink_M40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./RussianTurkey4-ea.lp > logs/con-RussianTurkey4-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./RussianTurkey40-ea.lp > logs/con-RussianTurkey40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./StolenCar2-ea.lp > logs/con-StolenCar2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./StolenCar40-ea.lp  --project > logs/con-StolenCar40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./StuffyRoom2-ea.lp > logs/con-StuffyRoom2-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./StuffyRoom40-ea.lp > logs/con-StuffyRoom40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./Supermarket12-ea.lp > logs/con-Supermarket12-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./Supermarket40-ea.lp > logs/con-Supermarket40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit1-ea.lp > logs/con-ThielscherCircuit1-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit20-ea.lp > logs/con-ThielscherCircuit20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ../axioms/causal.lp ./ThielscherCircuit40-ea.lp > logs/con-ThielscherCircuit40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./WalkingTurkey3-ea.lp > logs/con-WalkingTurkey3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./WalkingTurkey40-ea.lp > logs/con-WalkingTurkey40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./Yale3-ea.lp > logs/con-Yale3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./Yale40-ea.lp > logs/con-Yale40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./FallingObjectWithAntiTrajectory5-ea.lp > logs/con-FallingObjectWithAntiTrajectory5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./FallingObjectWithAntiTrajectory15-ea.lp > logs/con-FallingObjectWithAntiTrajectory15-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./FallingObjectWithAntiTrajectory25-ea.lp > logs/con-FallingObjectWithAntiTrajectory25-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./FallingObjectWithEvents5-ea.lp > logs/con-FallingObjectWithEvents5-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./FallingObjectWithEvents20-ea.lp > logs/con-FallingObjectWithEvents20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./FallingObjectWithEvents25-ea.lp > logs/con-FallingObjectWithEvents25-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./FallingObjectWithEvents40-ea.lp > logs/con-FallingObjectWithEvents40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./HotAirBalloon3-ea.lp > logs/con-HotAirBalloon3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./HotAirBalloon15-ea.lp > logs/con-HotAirBalloon15-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./HotAirBalloon20-ea.lp > logs/con-HotAirBalloon20-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./HotAirBalloon40-ea.lp > logs/con-HotAirBalloon40-ea.log 2>&1 ; exit 0

	python ../hec-incr.py --con ./Telephone3-ea.lp > logs/con-Telephone3-ea.log 2>&1 ; exit 0
	python ../hec-incr.py --con ./Telephone40-ea.lp > logs/con-Telephone40-ea.log 2>&1 ; exit 0
